# Generated by Django 4.1.3 on 2023-02-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cardthree_cardtwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardone',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
