# Generated by Django 4.1.3 on 2023-02-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cardone_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardone',
            name='amount',
        ),
    ]
