# Generated by Django 4.1.3 on 2023-02-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cardone_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=40)),
                ('middlename', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('dateofbirth', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CardOne',
        ),
        migrations.DeleteModel(
            name='CardThree',
        ),
        migrations.DeleteModel(
            name='CardTwo',
        ),
    ]
