# Generated by Django 4.1.3 on 2023-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_admission_delete_cardone_delete_cardthree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='firstname',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admission',
            name='lastname',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admission',
            name='middlename',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
