# Generated by Django 4.1.3 on 2023-02-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_admission_firstname_alter_admission_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='lastname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='middlename',
            new_name='mname',
        ),
    ]
