# Generated by Django 4.1.3 on 2023-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_admission_fname_alter_admission_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='fname',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admission',
            name='lname',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mname',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admission',
            name='sno',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
