# Generated by Django 4.1.3 on 2023-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_admission_fname_alter_admission_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
