# Generated by Django 4.1.3 on 2023-02-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_admission_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='fname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='admission',
            name='lname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mname',
            field=models.CharField(max_length=40),
        ),
    ]
