# Generated by Django 4.1.3 on 2023-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFrom',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=30)),
                ('dob', models.DateField(max_length=20)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
