# Generated by Django 4.1.3 on 2023-02-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionfrom',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
